name: PR golangci-lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working-directory:
          - ""
          - test
          - hack/tools
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # tag=v4.2.0
      - name: Calculate go version
        id: vars
        run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # tag=v5.0.2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # tag=v6.1.1
        with:
          version: v1.60.2
          args: --out-format=colored-line-number
          working-directory: ${{matrix.working-directory}}
