name: PR check Markdown links

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - '**.md'

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # tag=v4.2.1
    - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # tag=v1
      with:
        use-quiet-mode: 'yes'
        config-file: .markdownlinkcheck.json
        check-modified-files-only: 'yes'
        base-branch: main
