name: PR title verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # tag=v4.2.1

      - name: Check if PR title is valid
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          ./hack/verify-pr-title.sh "${PR_TITLE}"

