name: PR title verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # tag=v4.2.0

      - name: Check if PR title is valid
        run: |
          ./hack/verify-pr-title.sh "${{ github.event.pull_request.title }}"

