name: Release test

# Note: This workflow does not build for releases. It attempts to build release binaries daily to ensure the repo
# is in a good state.

on:
  schedule:
    # Cron for every day at 12:00 UTC.
    - cron: "0 12 * * *"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  weekly-test-release:
    name: Test release
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, release-1.4, release-1.3 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # tag=v4.0.0
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Set env
        run:  echo "RELEASE_TAG=v9.9.9-fake" >> $GITHUB_ENV
      - name: Set fake tag for release
        run: |
          git tag ${{ env.RELEASE_TAG }}
      - name: Calculate go version
        run: echo "go_version=$(make go-version)" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # tag=v4.0.1
        with:
          go-version: ${{ env.go_version }}
      - name: Test release
        run: |
          make release